### ISSUE TITLE
Use `version.txt` to determine latest version

### ISSUE THREAD

**Issue by Alexhuszagh** [rb2nem/nem-docker#10]
We have been using docker run NEM nodes, and we'd love to switch over to this setup. One thing I noticed, however, is that this setup script uses a hardcoded version. This is fairly easy to replace by merely setting the version from `version.txt` from the download page. It would likely simplify some work on your end. I'll gladly submit a PR if this is desirable.

Our script for the download is something as follows:

```bash
# Find latest version and download latest versions
RUN export nem_domain=https://bob.nem.ninja &&              \
    export version=$(curl $nem_domain/version.txt) &&       \
    export nis_sig=$nem_domain/nis-$version.tgz.sig &&      \
    export nis_installer=$nem_domain/nis-$version.tgz &&    \
    curl $nis_sig -o nis-ncc.tgz.sig &&                     \
    curl $nis_installer -o nis-ncc.tgz
```

**Comment by rb2nem** [comment]
I thought I had answered this long ago, sorry for the delay....

The reason I am not keen to include this is that it complexifies management as you don't control which version is deployed. What is you start a new node, and there's just been a new version released with incompatible changes without you knowing? One incompatible change I can think of is when the signature method of the release was changed from pgp to on-chain. Had this change been incorporated, all new nodes started would have failed as the scripts needed to be updated (they would have tried to validated the new release signature with the old signature scheme).
