### ISSUE TITLE
boot.sh fails at checksum stage

### ISSUE THREAD

**Issue by naetkss** [rb2nem/nem-docker#11]
Hello, i am run boot.sh ncc and get error: 
Step 6/19 : RUN sha=$(curl -L -s http://bigalice3.nem.ninja:7890/transaction/get?hash=$(curl -L -s  http://bob.nem.ninja/nis-0.6.95.tgz.sig | grep txId | sed -e 's/txId: //') | jq -r '.transaction.message.payload[10:74]') &&     echo "$sha nis-0.6.95.tgz"  > /tmp/sum &&     sha256sum -c /tmp/sum
 ---> Running in 35abc973e91c
sha256sum: /tmp/sum: no properly formatted SHA256 checksum lines found
The command '/bin/sh -c sha=$(curl -L -s http://bigalice3.nem.ninja:7890/transaction/get?hash=$(curl -L -s  http://bob.nem.ninja/nis-0.6.95.tgz.sig | grep txId | sed -e 's/txId: //') | jq -r '.transaction.message.payload[10:74]') &&     echo "$sha nis-0.6.95.tgz"  > /tmp/sum &&     sha256sum -c /tmp/sum' returned a non-zero code: 1

Help me pls. Thanks

**Comment by rb2nem** [comment]
The command line you run was used to start NCC, the old nem client. It is deprecated though, and you should now use the nano wallet: https://nem.io/downloads/
