### ISSUE TITLE
how get test nem coin in docker ?

### ISSUE THREAD

**Issue by naetkss** [rb2nem/nem-docker#12]
how get test nem coin in docker ?

**Comment by rb2nem** [comment]
Not sure I understand your question.
You can use nem-docker to start a node (NIS) on the test net, and use nano wallet to use that node. To get XEMs on the test net, ask it in the forum: https://forum.nem.io/t/paste-you-address-here-for-beta-nem-testnet-xem/829

Reopen the issue if this is not what you meant.
