### ISSUE TITLE
May change memory allocation size in supervisord.conf.sample

### ISSUE THREAD

**Issue by tokusyu** [rb2nem/nem-docker#13]
Nem NIS 0.6.96 is recommended to be allocated at least 2GB memory.
How about changing a value in "supervisord.conf.sample"?
https://forum.nem.io/t/nem-beta-0-6-96/18726

Actually my environment, NIS 0.6.96 is unstable in syncing when I launched it on default memory size.

**Comment by rb2nem** [comment]
This has been updated following a pull request. Sorry for the delay in tackling this.
