### ISSUE TITLE
installer fails and container is unusable with host user != 1000

### ISSUE THREAD

**Issue by nicman23** [rb2nem/nem-docker#14]
If you create an user with for example uid 1017, the ./boot.sh and Dockerfile are hard coded to use UID 1000

A better solution is to get uid from host in ./boot.sh and sed it on the dockerfile before the install

**Comment by rb2nem** [comment]
Your suggestion is good but I'm not inclined to implement it for the following reasons:
- the boot.sh sets the userid of the nem directory to 1000, so it works currently even if it's not perfect
- changing this my impact existing users
- lack of time to validate and debug scenario impacted by this change
