### ISSUE TITLE
Docker run testnet

### ISSUE THREAD

**Issue by riyazlafir** [rb2nem/nem-docker#15]
Hi,
How can I run testnet in docker image ? When I run docker rb2nem/nis image by default it runs mainnet.

Thanks.

**Comment by rb2nem** [comment]
You should be able to run on testnet using a [custom](https://github.com/rb2nem/nem-docker#tweaking-the-config) nis [config file](https://github.com/rb2nem/nem-docker/blob/master/custom-configs/nis.config-user.properties.sample) that includes the `nem.network` directive as described [here](https://forum.nem.io/t/how-to-run-a-nis-on-testnet/18436).
