### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by rmtodd618** [rb2nem/nem-docker#4]
Line 33 of boot.sh has an issue. You need a space between the following.
7880:7880-p

**Comment by rb2nem** [comment]
Indeed, I had this and other changes uncommitted in my local version. All pushed now!

**Comment by rmtodd618** [comment]
Cool. Do you have a super node running on the docker image yourself?

**Comment by rb2nem** [comment]
Yes. Running both nis and ncc with these scripts.

**Comment by rmtodd618** [comment]
I have an issue with configuring the nis config file. It quits working.

**Comment by rb2nem** [comment]
The nis config file name has changed,  check the name of the sample config file and remove ".sample"  from it. Is that the problem?
