### ISSUE TITLE
boot.sh fails at checksum stage

### ISSUE THREAD

**Issue by BenUniqcode** [rb2nem/nem-docker#7]
Hi
I previously used nem-docker successfully, but I'm trying to do so again and it's now failing during boot.sh:

    Step 6/19 : RUN sha=$(curl -s http://bigalice3.nem.ninja:7890/transaction/get?hash=$(curl -s  http://bob.nem.ninja/nis-ncc-0.6.87.tgz.sig | grep txId | sed -e 's/txId: //') | jq -r '.transaction.message.payload[10:]') &&     echo "$sha nis-ncc-0.6.87.tgz"  > /tmp/sum &&     sha256sum -c /tmp/sum
     ---> Running in 31ee04c5dac3
    sha256sum: /tmp/sum: no properly formatted SHA256 checksum lines found
    The command '/bin/sh -c sha=$(curl -s http://bigalice3.nem.ninja:7890/transaction/get?hash=$(curl -s  http://bob.nem.ninja/nis-ncc-0.6.87.tgz.sig | grep txId | sed -e 's/txId: //') | jq -r '.transaction.message.payload[10:]') &&     echo "$sha nis-ncc-0.6.87.tgz"  > /tmp/sum &&     sha256sum -c /tmp/sum' returned a non-zero code: 1

I believe the problem is that bigalice3 is not responding to the request for the transaction. The inner curl (to bob) works fine, but the outer one just sits there for ages and then eventually times out and returns nothing.

Obviously I can just bypass the hash check (or do it manually) by commenting it out of the Dockerfile... but is there any way to get rid of this dependency on a single host? Or failing that, can it be changed to one that works? :)

Cheers
Ben

**Comment by rb2nem** [comment]
This seems to have been a temporary problem with the node used (just tested now and it worked fine). I will try to find a solution to not fail if bigalice3 does not answer.

**Comment by rb2nem** [comment]
Leaving as is now, will work on it if causes further problems
