### ISSUE TITLE
Error: Restarting NCC all day long

### ISSUE THREAD

**Issue by vuemaster** [rb2nem/nem-docker#9]
Hello
1) NIS is running and harvesting on 2 slots perfectly and Blockheight is synced.
2) Tried to start ncc with sudo ./supervisorctl.sh -> start ncc -> status
    which resulted in 

```
> ncc   STARTING
> ncc   RUNNING   pid 1226, uptime 0:00:01
> ncc   STARTING
```

....

if I look into the log in .../nem folder ncc.stderr.log I find the following:
```
Error: Could not find or load main class org.nem.deploy.CommonStarter
Error: Could not find or load main class org.nem.deploy.CommonStarter
Error: Could not find or load main class org.nem.deploy.CommonStarter
```
....
until the end

So what can I do so that the ncc is starting?

**Comment by rb2nem** [comment]
NCC is clearly deprecated now, so I'll close this ticket.
